# Github Actions to create a release and upload a release asset
# Uploads a zip file to the release created conversor-moedas-java.zip

on:
  push:    
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Uploud EFI to Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Packaging project to zip
        run: |
          zip -q -r *.zip ./* --exclude=*.git*
          ls -l *.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: changelog.md
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./*.zip
          asset_name: conversor-moedas.zip
          asset_content_type: application/zip